### PR TITLE
circleci: add config

### PR DESCRIPTION
**Pull request by kopiczko**

### CODE REVIEW

**Comment by kopiczko** [comment]
@xh3b4sd I added the badge, PRs merge is protected with CI check. Is there anything left?

**Comment by xh3b4sd** [comment]
Should be good.

**Comment by xh3b4sd** [comment]
You only used the "wrong" badge. I don't like this one personally because the other one is more fancy.

**Comment by kopiczko** [comment]
I generated it from here: https://circleci.com/gh/giantswarm/tprstorage/edit#badges

I'd change that, but I don't know how.

**Comment by kopiczko** [comment]
https://github.com/giantswarm/tprstorage/pull/10

**Pull request merged**
